[DEFAULT]
transport_url = rabbit://openstack:<URL_ENCODED_PASSWORD>@controller
auth_strategy = keystone
my_ip = 192.168.234.150
glance_api_servers = http://controller:9292
enabled_backends = lvm
default_volume_type = lvm

[database]
connection = mysql+pymysql://cinder:<URL_ENCODED_PASSWORD>@controller/cinder

[keystone_authtoken]
www_authenticate_uri = http://controller:5000
auth_url = http://controller:5000
memcached_servers = controller:11211
auth_type = password
project_domain_name = Default
user_domain_name = Default
project_name = service
username = cinder
password = <SERVICE_PASSWORD>

[oslo_concurrency]
lock_path = /var/lib/cinder/tmp

[lvm]
volume_driver = cinder.volume.drivers.lvm.LVMVolumeDriver
volume_group = cinder-volumes
target_protocol = iscsi
target_helper = lioadm
target_ip_address = 192.168.234.150
volume_backend_name = LVM-ISCSI
